### PR TITLE
fix: allow false values to keepLambdaLogs

### PR DESCRIPTION
**Pull request by perrin4869**
Thanks for the plugin!
`keepLambdaLogs` would only accept true values, this should fix it!

### CODE REVIEW

**Review by jduncan-xoi — APPROVED** [review]
Ah I love it!

**Comment by perrin4869** [comment]
Thanks! As soon as you cut a release I'll implement this in my project :)

**Comment by jduncan-xoi** [comment]
> Thanks! As soon as you cut a release I'll implement this in my project :)

We published 1.0.1, @perrin4869, check it out and let me know if you find anything else. Thanks again!

**Comment by perrin4869** [comment]
@jduncan-xoi thanks!
I did have further problems using this plugin.The reason is that I need to keep the logs based on the environment, so do something like `keepLambdaLogs: ${param:keepLambdaLogs}`, but this plugin checks the param in the plugin contstructor, before it is evaluated - this is referred to in the [docs](https://www.serverless.com/framework/docs/guides/plugins/custom-configuration):

```
Note: configuration values are only resolved after plugins are initialized. Do not try to read configuration in the plugin constructor, as variables aren't resolved yet. Read configuration in lifecycle events only.
```

I could fix this, but then the tests would break... And would require a rather extensive test rewrite, maybe similar to https://github.com/theBenForce/serverless-rollup-plugin/blob/master/test/index.ts

**Pull request merged**
